[package]
name = "fuscia-trigger"
edition.workspace = true
version.workspace = true

[dependencies]
fuscia-component-registry = { path = "../fuscia-component-registry" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
