[package]
name = "fuscia"
edition.workspace = true
version.workspace = true

[[bin]]
name = "fuscia"
path = "src/main.rs"

[workspace]
package.edition = "2024"
package.version = "0.0.1-alpha.0"
exclude = [
  "test-components/test-task-component",
  "test-components/test-trigger-component",
]
members = [
  "crates/fuscia-artifact",
  "crates/fuscia-component-registry",
  "crates/fuscia-config",
  "crates/fuscia-engine",
  "crates/fuscia-host",
  "crates/fuscia-resolver",
  "crates/fuscia-store",
  "crates/fuscia-task",
  "crates/fuscia-task-host",
  "crates/fuscia-trigger",
  "crates/fuscia-trigger-host",
  "crates/fuscia-workflow",
  "crates/fuscia-world",
]

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "6"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
serde_json = "1"
anyhow = "1"

fuscia-config = { path = "crates/fuscia-config" }
fuscia-component-registry = { path = "crates/fuscia-component-registry" }
fuscia-resolver = { path = "crates/fuscia-resolver" }
fuscia-engine = { path = "crates/fuscia-engine" }
