[package]
name = "fuscia"
edition.workspace = true
version.workspace = true

[workspace]
package.edition = "2024"
package.version = "0.0.1-alpha.0"
exclude = [
  "test-components/test-task-component",
  "test-components/test-trigger-component",
]
members = [
  "crates/fuscia-artifact",
  "crates/fuscia-component",
  "crates/fuscia-config",
  "crates/fuscia-engine",
  "crates/fuscia-host",
  "crates/fuscia-resolver",
  "crates/fuscia-store",
  "crates/fuscia-task",
  "crates/fuscia-task-host",
  "crates/fuscia-trigger",
  "crates/fuscia-trigger-host",
  "crates/fuscia-workflow",
  "crates/fuscia-world",
]

[dependencies]
