[package]
name = "fuscia"
edition.workspace = true
version.workspace = true

[workspace]
package.edition = "2024"
package.version = "0.0.1-alpha.0"
members = ["crates/fuscia-artifact","crates/fuscia-config"
, "crates/fuscia-store"]

[dependencies]
