[package]
name = "fuscia-world"
edition.workspace = true
version.workspace = true

[dependencies]
wasmtime = { version = "40", features = ["component-model", "async"] }
wasmtime-wasi = { version = "40" }
