[package]
name = "test-trigger-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.41"

[package.metadata.component]
package = "fuschia:test-trigger"

[package.metadata.component.dependencies]
