[package]
name = "fuschia-trigger"
edition.workspace = true
version.workspace = true

[dependencies]
fuschia-component-registry = { path = "../fuschia-component-registry" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
