[package]
name = "test-task-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.41"

[package.metadata.component]
package = "fuscia:test-task"

[package.metadata.component.dependencies]
